### ISSUE TITLE
Allow installation in a MyISAM database

### ISSUE THREAD

**Issue by ivangretsky** [BitPoet/JsonNativeField#4]
Good day and thanks for a promising module I was waiting to try for a several years) I thought now was THE time, but the fact that my database is primarily MyISAM seems to stop me) When I try to install the module, I get this error: **Modules: Unable to install module (FieldtypeJsonNative): InnoDB database engine needs to be used for native JSON support**.

I know that some modules that need InnoDB tables just create them. Like Hanna Code and Pro Cache. I wish I could use JsonNativeField on existing installations like the mentioned modules, Do you think it would be possible to achieve that?

**Comment by BitPoet** [comment]
The new version in the [dev tree](https://github.com/BitPoet/JsonNativeField/tree/dev) is without the MyISAM check and should install okay. Needs some testing though before I merge it into the master tree.

**Comment by ivangretsky** [comment]
Got it installed. Should I close this one or wait till it hits the master branch?

**Comment by BitPoet** [comment]
Thanks for the feedback. I've merged the changes into the master branch.

**Comment by ivangretsky** [comment]
Cool!
